### POST create a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Roe Kafka New",
  "email": "doe4@mail.com",
  "address": "123 m s",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-29"
}
###